Changes related to ROOT file
GASP-UFRGS/LHE-Proton-Writer pull request #8
Opened 2024-03-06 20:00 UTC by Artur-UF

Added a ROOT file for testing and an input file to be used with root generator and plotter

2024-03-10 15:51 UTC, diemort requested changes

2024-03-10 15:51 UTC, diemort commented on Validation/root_gen.py
> +rootinput = np.loadtxt('root_input.txt', unpack=True, dtype=str, delimiter='=')
how the root file comes here? not from input file?

Add this input root to the input file to allow user to quick run.

2024-03-10 15:51 UTC, diemort commented on Validation/root_input.txt
> +# CROSS SECTION(S) (pb):
to this list make sense, you have to add the input root files here as a list.

this list can also append the name of the generator in case there's a mix of samples

2024-04-01 19:59 UTC, Artur-UF commented on Validation/root_input.txt
> +# CROSS SECTION(S) (pb):
what input root files? do you mean the name of the 1D and 2D arrays?

and append the name of the generator to what? the name of the .root?

2024-04-01 20:58 UTC, Artur-UF commented on Validation/root_gen.py
> +rootinput = np.loadtxt('root_input.txt', unpack=True, dtype=str, delimiter='=')
what root file? the .root is created at the end of this .py

2024-04-02 01:23 UTC, merged